url: "https://harshnahar.com"
baseurl: ""
title: "harsh nahar"
permalink: /blog/:title/

# Blog posts defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Gallery collection defaults
collections:
  gallery:
    output: true
    permalink: /gallery/:title/

defaults:
  - scope:
      path: ""
      type: "gallery"
    values:
      layout: "gallery_posts"
